import { Mulish, Public_Sans } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Providers } from "@/lib/providers";

const publicSans = Public_Sans({ subsets: ["latin"] });
const mulish = Mulish({ subsets: ["latin"] });

export const metadata = {
  title: "Employlynk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${publicSans.className} ${mulish.className} antialiased`} suppressHydrationWarning={true}>
        <Providers>
          <Header />
          <main className="container min-h-screen w-full mx-4 lg:mx-8">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
